tests:
    hello:
        assertStdoutEqual: "Hello World"
        input:
            - ""
software:
    python:
        execute: ["python3", "HelloWorld.py", "[[tests]]"]
    bash:
        execute: ["bash", "HelloWorld.sh", "[[tests]]"]
    perl:
        execute: ["perl", "HelloWorld.pl", "[[tests]]"]
    #php:
    #    execute: ["php", "HelloWorld.php", "[[tests]]"]
    #ruby:
    #    execute: ["ruby", "HelloWorld.rb", "[[tests]]"]
    #javascript:
    #    execute: ["node", "HelloWorld.js", "[[tests]]"]
    #go:
    #    execute: ["go", "run", "HelloWorld.go", "[[tests]]"]
    #html:
    #    execute: ["lynx", "--dump", "HelloWorld.html#[[tests]]"]
