settings:
  log: slack
  
tests:
  assertStdoutEqual: Hello World
  assertCommandExists: True

  input:
    - Hello World
  python:
    - [ python3 HelloWorld.py ]
  custom:
    - [ python3 a_test.py $(input) ]
  bash:
    - [ bash HelloWorld.sh ]
  perl:
    - [ perl HelloWorld.pl ]
