settings:
  log: slack
  
tests:
  assertStdoutEqual: Hello World
  assertCommandExists: True

  input:
    - Hello World
  python:
    - [ python3 HelloWorld.py ]
  bash:
    - [ bash HelloWorld.sh ]
  perl:
    - [ perl HelloWorld.pl ]
