settings:
  image: nikolaik/python-nodejs

#install:
#  - apt update
#  - apt install -qy php php-common nodejs
  
tests:
  assertStdoutContains: Hello World
  assertCommandExists: True
  
  bash:
    - bash HelloWorld.sh
  javascript:
    - node HelloWorld.js
  perl:
    - perl HelloWorld.pl
  php:
    - php HelloWorld.php 
  python:
    - python3 HelloWorld.py
