install:
  assertReturnCode: 0
  php:
  - apt -y install php php-common node
  
tests:
  assertStdoutContains: Hello World
  assertCommandExists: True
  
  bash:
    - bash HelloWorld.sh
  javascript:
    - node HelloWorld.js
  perl:
    - perl HelloWorld.pl
  php:
    - php HelloWorld.php 
  python:
    - python3 HelloWorld.py
