tests:
        hello:
                assertStdoutEqual: "Hello World"
                input:
                        - 2
software:
        python:
                execute: ["python3", "HelloWorld.py"]
        bash:
                execute: ["bash", "HelloWorld.sh"]
        install:
                - git clone https://github.com/satorici/Hello-World
                - cd Hello-World
