install:
  fail:
    - [echo This works]
    - [this-does-not]
    - [echo This should not even appear]

tests:
  assertStdoutEqual: Hello World
  assertSoftwareExists: True

  input:
    - Hello World
    - Hello Earth
  python:
    - [python3 HelloWorld.py]
  custom:
    - [python3 a_test.py $(input)]
  error:
    - [aaaa]
    - [echo test && aaaa]

