tests:
        hello:
                assertStdoutEqual: "Hello World"
                input:
                        - ""
                test:
                        - [[hello]]
software:
        python:
                execute: ["python3", "HelloWorld.py[[tests]]"]
        bash:
                execute: ["bash", "HelloWorld.sh[[tests]]"]
        install:
                - git clone https://github.com/satorici/Hello-World
                - cd Hello-World
