tests:
  assertStdoutEqual: Hello Earth
  assertReturnCode: 0

  greet:
    - Hello World
    - mutate: radamsa
      mutate_qty: 4
      value: Hello Earth

  python:
    - [python3, HelloWorld.py]

  custom:
    - [python3, a_test.py, $(greet)]
