tests:
        hello:
                assertStdoutEqual: "Hello World"
                input:
                        - 2
software:
        python:
                execute: ["python3", "Hello-World/HelloWorld.py", "[[tests]]"]
                install: 
                        - git clone https://github.com/satorici/Hello-World
        bash:
                execute: ["bash", "Hello-World/HelloWorld.sh", "[[tests]]"]
                install:
                        - git clone https://github.com/satorici/Hello-World
