settings:
  image: nikolaik/python-nodejs
  
tests:
  assertStdoutContains: Hello World
  assertCommandExists: True
  
  bash:
    - bash HelloWorld.sh
  javascript:
    - node HelloWorld.js
  perl:
    - perl HelloWorld.pl
  python:
    - python3 HelloWorld.py
