settings:
  log: slack

install:
  assertReturnCode: 0
  php:
  - [ apt -y install php php-common ]
  
tests:
  assertStdoutContains: Hello World
  assertCommandExists: True
  
  python:
    - [ python3 HelloWorld.py ]
  bash:
    - [ bash HelloWorld.sh ]
  perl:
    - [ perl HelloWorld.pl ]
  php:
    - [ php HelloWorld.php ] 

