tests:
  assertStdoutEqual: Hello World
  assertSoftwareExists: True

  input:
    - Hello World
    - Hello Earth
  python:
    - [python3 HelloWorld.py]
  custom:
    - [python3 a_test.py $(input)]
