tests:
        assertStdout: "Hello World"
        input:
                - ""
software:
        python:
                execute: ["python", "HelloWorld.py"]
        bash:
                execute: ["bash", "HelloWorld.sh"]
        install:
                - git clone https://github.com/satorici/Hello-World
                - cd Hello-World
